In [3]:
import numpy as np

# `1) Write a program to create a 5 dimensional array with all zeros and ones`


In [40]:
a=np.zeros((2,3,2,5,5)) 
a=a.astype(int)   # Convert the resulting array to integers
a

array([[[[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]],

         [[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]],


        [[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]],

         [[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]],


        [[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]],

         [[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]]],



       [[[[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]],

         [[0, 0, 0, 0, 0],
      

In [41]:
a1=np.ones((2,3,2,5,5)) 
a1=a1.astype(int)
a1

array([[[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]],


        [[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]],


        [[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]]],



       [[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
      

## `2) Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)`


In [43]:
b = np.array([np.zeros(10), np.ones(10), np.full(10, 5)])
b = b.astype(int)
b

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [44]:
b.shape

(3, 10)

## `3) Write a program to create a 3x4 matrix filled with values from 10 to 21`


In [74]:
c=np.arange(10,22)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [75]:
c=np.arange(10,22).reshape(3,4)
c

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

## `4) Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,`


In [18]:
d = np.zeros((10, 10))

np.fill_diagonal(d, np.arange(10))
d = d.astype(int)                    # Convert the resulting array to integers
d


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

## `5)Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns`


In [166]:
d=np.arange(1,17).reshape(4,4)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [185]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

arr[:, [0, 3]] = arr[:, [3, 0]]

arr[:, [1, 2]] = arr[:, [2, 1]]

print(arr)


[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


## `6) Write a program to reverse an array (the first element becomes the last)`
### Given array:
### [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]


In [189]:
a=np.arange(12,28)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [194]:
a[::-1]


array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

## `7) Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100`


In [21]:
a=np.arange(1,101).reshape(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [22]:
w=a[np.where((a > 30) & (a < 80) & (a % 5 == 0))]   #to find elements in the array that satisfy the conditions
w

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

# `8) Write a program to create a 2D array with 1 on the border and 0 inside`


In [209]:
rows, cols = 5, 5

array_2d = np.ones((rows, cols))
array_2d[1:-1, 1:-1] = 0

array_2d = array_2d.astype(int)

print(array_2d)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## `9) Write a program to create a checkerboard pattern .Don't use default array function`
## `Checkerboard pattern`   


In [38]:
size = 8

checkerboard = np.zeros((size, size), dtype=int)

for i in range(size):
    for j in range(size):
        if (i + j) % 2 == 1:
            checkerboard[i, j] = 1

print("Checkerboard Pattern:")
print(checkerboard)

Checkerboard Pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## `10) Write a program to find common values between two arrays`
### Expected Output:
## array1: [10 20 40 60]
## array2: [10, 30, 40,50]


In [219]:
arr1=np.array([10,20,40,60])
arr2=np.array([10,30,40,50])
arr1,arr2

(array([10, 20, 40, 60]), array([10, 30, 40, 50]))

In [221]:
i=np.intersect1d(arr1,arr2)
i

array([10, 40])

## `11) Write a program to create an array 2d array and then reshape into 1d array`


In [48]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
print(arr.ndim)

2


In [50]:
new=arr.flatten()        # will convert the 2D array into a 1D array.
new

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
print(new.ndim)

1
